# Generated by Django 3.0.6 on 2020-06-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200602_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
