# Generated by Django 3.0.6 on 2020-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1, verbose_name='Experience'),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Puplished At'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='Salary'),
        ),
        migrations.AddField(
            model_name='job',
            name='vacanvy',
            field=models.IntegerField(default=1, verbose_name='Vacanvy'),
        ),
    ]
