# Generated by Django 3.0.6 on 2020-06-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=0, upload_to='jobs/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
