# Generated by Django 3.0.6 on 2020-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20200608_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='vacanvy',
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=1, verbose_name='Vacancy'),
        ),
    ]
